UmbracoHomework/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UmbracoHomework.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            for (int i = 0; i < 100; i++)
            {
                Console.WriteLine("hej");
            }

            return View();
        }

       
    }
}

UmbracoHomework/Controllers/SubmissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UmbracoHomework;

namespace UmbracoHomework.Controllers
{
    public class SubmissionsController : Controller
    {
        private AcmeDBEntities db = new AcmeDBEntities();


        public JsonResult IsUserNameAvailable(string FirstName)
        {
            using (var db = new AcmeDBEntities())
            {
                return Json(!db.SubmissionSet.Any(name => name.FirstName == FirstName), JsonRequestBehavior.AllowGet);

            }


        }


        public JsonResult IsSerialnumberAvailable(Guid? Serialnumber)
        {
            if (!Serialnumber.HasValue) return Json(false, JsonRequestBehavior.AllowGet);

            using (var db = new AcmeDBEntities())
            {
                var serial = db.Serialnumber.FirstOrDefault(x => x.Serialnumber1 == Serialnumber);
                return Json(serial.Counter > 0, JsonRequestBehavior.AllowGet);
            }

        }

        // GET: Submissions
        public ActionResult Index()
        {

            using (var db = new AcmeDBEntities())
            {
                var submissionSet = db.SubmissionSet.Include(s => s.Serialnumber1);
                return View(submissionSet.ToList());
            }

        }

        // GET: Submissions/Details/5
        //public ActionResult Details(int? id)
        //{
        //    using (var db = new AcmeDBEntities())
        //    {
        //        if (id == null)
        //        {
        //            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //        }
        //        Submission submission = db.SubmissionSet.Find(id);
        //        if (submission == null)
        //        {
        //            return HttpNotFound();
        //        }
        //        return View(submission);
        //    }
        //}

        // GET: Submissions/Create
        public ActionResult Create()
        {

            using (var db = new AcmeDBEntities())
            {
                ViewBag.Serialnumber = new SelectList(db.Serialnumber, "Serialnumber1", "Serialnumber1");



                return View();

            }
        }

        // POST: Submissions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,Age,Serialnumber,DOB")] Submission submission)
        {

            if (ModelState.IsValid)
            {                
                try
                {
                   

                    db.SubmissionSet.Add(submission);
                    var serial = db.Serialnumber.First(x => submission.Serialnumber == x.Serialnumber1);
                    serial.Counter--;
                    
                    db.SaveChanges();
                    return RedirectToAction("Draw");
                }

                catch (Exception e)
                {
             
                }
            }
        


    

    ViewBag.Serialnumber = new SelectList(db.Serialnumber, "Serialnumber1", "Serialnumber1", submission.Serialnumber);
          

            return View(submission);
}

// GET: Submissions/Edit/5
//public ActionResult Edit(int? id)
//{
//    if (id == null)
//    {
//        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//    }
//    Submission submission = db.SubmissionSet.Find(id);
//    if (submission == null)
//    {
//        return HttpNotFound();
//    }
//    ViewBag.Serialnumber = new SelectList(db.Serialnumber, "Serialnumber1", "Serialnumber1", submission.Serialnumber);
//    return View(submission);
//}

// POST: Submissions/Edit/5
// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
//[HttpPost]
//[ValidateAntiForgeryToken]
//public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,Age,Serialnumber,DOB")] Submission submission)
//{
//    if (ModelState.IsValid)
//    {
//        db.Entry(submission).State = EntityState.Modified;
//        db.SaveChanges();
//        return RedirectToAction("Index");
//    }
//    ViewBag.Serialnumber = new SelectList(db.Serialnumber, "Serialnumber1", "Serialnumber1", submission.Serialnumber);
//    return View(submission);
//}

// GET: Submissions/Delete/5
public ActionResult Delete(int? id)
{
    if (id == null)
    {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
    }
    Submission submission = db.SubmissionSet.Find(id);
    if (submission == null)
    {
        return HttpNotFound();
    }
    return View(submission);
}

// POST: Submissions/Delete/5
[HttpPost, ActionName("Delete")]
[ValidateAntiForgeryToken]
public ActionResult DeleteConfirmed(int id)
{
    Submission submission = db.SubmissionSet.Find(id);
    db.SubmissionSet.Remove(submission);
    db.SaveChanges();
    return RedirectToAction("Index");
}

protected override void Dispose(bool disposing)
{
    if (disposing)
    {
        db.Dispose();
    }
    base.Dispose(disposing);
}

// DRAW
public ActionResult Draw()
{
    return View();
}

    }

 
}

UmbracoHomework/Controllers/ValidationController.cs
////using System;
////using System.Collections.Generic;
////using System.Globalization;
////using System.Linq;
////using System.Web;
////using System.Web.Mvc;
////using System.Web.UI;

////namespace UmbracoHomework.Controllers
////{
  

////        [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]

////        public class ValidationController : Controller
////        {

////        private AcmeDBEntities db = new AcmeDBEntities();

////        public ValidationController() : this(db.Instance) { }



////            public ValidationController(IUserDB repository)
////            {
////                _repository = repository;
////            }

////            public JsonResult IsUID_Available(string Username)
////            {

////                if (!_repository.UserExists(Username))
////                    return Json(true, JsonRequestBehavior.AllowGet);

////                string suggestedUID = String.Format(CultureInfo.InvariantCulture,
////                    "{0} is not available.", Username);

////                for (int i = 1; i < 100; i++)
////                {
////                    string altCandidate = Username + i.ToString();
////                    if (!_repository.UserExists(altCandidate))
////                    {
////                        suggestedUID = String.Format(CultureInfo.InvariantCulture,
////                       "{0} is not available. Try {1}.", Username, altCandidate);
////                        break;
////                    }
////                }
////                return Json(suggestedUID, JsonRequestBehavior.AllowGet);
////            }

////        }
////    }

UmbracoHomework/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Acme Corporation</h1>
    <p class="lead">Enter the draw by creating a submission if you have a valid serial number so you can purchase one of Acme Cooporation's products. You can only enter the draw if you have a valid serial number</p>
    <p><a href="/submissions/create" class="btn btn-primary btn-lg">Submit</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>About</h2>
        <p>
            This website is developed using ASP.NET, Visual Studio 2017 and SQL Server Management. 
            Also there is used a EntityFramework for the database. 
        </p>
    </div>
    <div class="col-md-4">
        <h2>To-Do's/Done</h2>
        <p>
            - Create a web application and secondary project for test and class library content
           <br /> - Create a database to store information for the draw
           <br /> - Generate 100 valid serial numbers
           <br /> - Create a submission form on a web page (data needs to be validated and stored in database)
           <br /> - Create a web page showing all submissions
           <br /> - Write unit tests for validating the form data to ensure the rules for entering the draw are followed
           <br /> - Write a readme.md

        </p>
    </div>
    <div class="col-md-4">
        <h2>AllSubmissions & Extra Info</h2>
        <p>There are generated 100 unique serialnumbers in the database. In this application if you want to submit you need a valid serialnumber and you can only use the serialnumber twice which is calculated through a counter in the database</p>
        <p><a class="btn btn-default" href="/Submissions">See List of Submissions &raquo;</a></p>
    </div>
</div>

UmbracoHomework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Acme Corportation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("All Submissions", "Index", "Submissions")</li>
                    <li>@Html.ActionLink("Submission Form", "Create", "Submissions")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

UmbracoHomework/Views/Submissions/Create.cshtml
@model UmbracoHomework.Submission

@{
    ViewBag.Title = "Submit";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<h2>Submit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Submission</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Serialnumber, "Serialnumber", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownList("Serialnumber", null, htmlAttributes: new { @class = "form-control" })*@


                @Html.EditorFor(model => model.Serialnumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Serialnumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />


            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

UmbracoHomework/Views/Submissions/Delete.cshtml
@model UmbracoHomework.Submission

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Submission</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serialnumber1.Serialnumber1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serialnumber1.Serialnumber1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UmbracoHomework/Views/Submissions/Draw.cshtml
@{
    ViewBag.Title = "Draw";
}

<h2>Congratilations! You've entered the draw!</h2>

UmbracoHomework/Views/Submissions/Index.cshtml
@model IEnumerable<UmbracoHomework.Submission>

@{
    ViewBag.Title = "Submissions";
}

<h2>Submissions</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Serialnumber1.Serialnumber1)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DOB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serialnumber1.Serialnumber1)
        </td>
        <td>
          
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>